name: Build and Release Rust Project

on:
  push:
    tags:
      - 'v*'  # 监听版本标签的推送，如 v1.0.0

jobs:
  build:
    name: Build for macOS and Linux
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  # Linux 和 macOS 构建环境
        target: [x86_64-unknown-linux-gnu, x86_64-apple-darwin]  # 构建目标

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable  # 使用 Rust stable 版本
          profile: minimal
          override: true

      - name: Install Dependencies
        run: |
          rustup target add ${{ matrix.target }}

      - name: Build Project
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sshm-${{ matrix.os }}
          path: target/${{ matrix.target }}/release/sshm  # 上传构建产物

  release:
    name: Create Release
    needs: build  # 等待构建完成后执行
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-latest-binary
          path: binaries/linux/
      
      - name: Download macOS Binary
        uses: actions/download-artifact@v3
        with:
          name: macos-latest-binary
          path: binaries/macos/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            binaries/linux/*
            binaries/macos/*
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}  # 使用 GitHub 自动生成的 Token
